### ISSUE TITLE
Building from source broken

### ISSUE THREAD

**Issue by dihm** [chrisjbillington/setuptools-conda#22]
Something has happened in the past month that now breaks the ability for `setuptools-conda` to build itself from source (see [action ](https://github.com/chrisjbillington/setuptools-conda/actions/runs/9118136034/job/25070567263) for full log).

Basic error returned is a file not found error `error: [Errno 2] No such file or directory: 'conda_build/setuptools-conda-0.15.1.dev5.tar.gz'`

I've reproduced this on a local windows machine. Failure is from this line
https://github.com/chrisjbillington/setuptools-conda/blob/51440f754779445ab5ef843ff856a77120a06622/setuptools_conda/setuptools_conda.py#L654
Frustratingly, the file definitely exists locally, and I can open a separate python REPL and confirm that `os.path.isfile(build_dir, dist)` returns True. If I run that command within the `dist_conda.run`, it returns False.

Checking a few likely suspects, it appears that downgrading `setuptools<69` fixes the issue.

**Comment by dihm** [comment]
Narrowed it down a little more. `setuptools==69.2.0` still works. Conda doesn't have any versions between that and current 69.5.1 which is broken.

**Comment by chrisjbillington** [comment]
If it's the same issue I can reproduce on Linux, the problem is that the sdist is created with an underscore in the project name part of the filename, rather than a dash. This looks like a deliberate decision from setuptools (at least, it's deliberate for wheels, and I guess sdists are following the same rules either intentionally or as a side effect):

https://github.com/pypa/setuptools/issues/4214

https://github.com/pypa/setuptools/issues/4167

The function `setuptools-conda` was using to get the name of the sdist file based on the project name (which has dashes in it) was therefore wrong. In 20e39f212076d8ab67d0a0f227de4977e179036d I've switched to use a different function to get the sdist name, which observably returns underscores instead. The return value of this function seems to be what is used to create the sdist and wheel names, so ought to be correct however the sdists are made (i.e. on both old and new setuptools versions).

If you could test that this solves the problem for  you as well, that'd be great, and I'll tag a new release.

Frustrating that the community can't make up its mind about dashes vs underscores.

**Comment by dihm** [comment]
It is sad really. I knew it was some sort of path issue, and I checked those two filenames at least 20 times, and still didn't notice the dashes vs the underscores. Brain just filters them out. Ugh. Maybe someday everyone can make up their minds...

I can confirm that the change you made fixes the issue.
